# Generated by Django 3.0.2 on 2020-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cough', models.CharField(max_length=30)),
                ('fever', models.CharField(max_length=30)),
                ('sore_throat', models.CharField(max_length=30)),
                ('breathing', models.CharField(max_length=30)),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='PredResults',
        ),
    ]
