# Generated by Django 3.0.2 on 2020-09-12 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20200912_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresults',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
