# Generated by Django 3.1 on 2020-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_predictionresults_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresults',
            name='user',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
